CTO-71 - Implementing CDAC Endpoint Inputs and Controllers for Streams, Stream Reaches, and Stream Locations
HydrologicEngineeringCenter/cwms-data-api-client pull request #191
Opened 2024-07-11 23:27 UTC by rma-bryson

Also include their unit tests

2024-07-11 23:46 UTC, adamkorynta requested changes

2024-07-11 23:46 UTC, adamkorynta commented on cwms-radar-client/src/test/java/mil/army/usace/hec/cwms/radar/client/controllers/TestStreamReachController.java
> +        Logger.getLogger("").setLevel(Level.ALL);
Why is the log level getting adjusted?

2024-07-12 14:39 UTC, rma-bryson commented on cwms-radar-client/src/test/java/mil/army/usace/hec/cwms/radar/client/controllers/TestStreamReachController.java
> +        Logger.getLogger("").setLevel(Level.ALL);
shouldn't be. Removed

2024-07-12 15:31 UTC, adamkorynta approved these changes

2024-07-12 15:33 UTC, merged